version: '3'

services:
  playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile

    image: playwright

    environment:
      - ENV_VARIABLE=value

    volumes:
      - .:/app

    ports:
      - "9323:9323"

    working_dir: /app
